---
trust-domain: xpi

task-priority: lowest

taskgraph:
    register: xpi_taskgraph:register
    repositories:
        # This is the manifest repo
        # string: for a source repo, this should match the `repo-prefix`
        #         in `xpi-manifest.yml`
        xpi:
            # string: the name of the repo, for humans
            name: "XPI manifest"
            # regex: to match the base name of the repo
            project-regex: test-xpi-manifest(\.git)?$
            # string: the repo url. Use `git@github.com:org/repo` for private
            #         repositories.
            default-repository: https://github.com/escapewindow/test-xpi-manifest
            # string: which branch is primary; should be `master`
            default-ref: master
            # enum: hg or git; should be `git`
            type: git
        normandydevtools:
            name: "Normandy Devtools"
            project-regex: normandy-devtools$
            default-repository: https://github.com/mozilla-extensions/normandy-devtools
            default-ref: master
            type: git
        private:
            name: "Private repo test"
            project-regex: test-xpi-private(\.git)?$
            default-repository: git@github.com:escapewindow/test-xpi-private
            default-ref: master
            type: git
        template:
            name: "template repo test"
            project-regex: test-xpi-public$
            default-repository: https://github.com/escapewindow/test-xpi-public
            default-ref: master
            type: git
        multipreffer:
            name: "Multipreffer"
            project-regex: multipreffer
            default-repository: https://github.com/mozilla/multipreffer
            default-ref: master
            type: git
        fingerprinting:
            name: "Fingerprinting and cryptomining protections retention study"
            project-regex: fingerprinting-cryptomining-retention-study
            default-repository: https://github.com/mozilla/fingerprinting-cryptomining-retention-study
            default-ref: master
            type: git
    cached-task-prefix: xpi

workers:
    aliases:
        b-linux:
            provisioner: xpi-{level}
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux'
        images:
            provisioner: xpi-{level}
            implementation: docker-worker
            os: linux
            worker-type: 'images'
        dep-signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type: xpi-t-signing
        signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type:
                by-level:
                    "3": xpi-3-signing
                    default: xpi-t-signing
        shipit:
            provisioner: scriptworker-k8s
            implementation: scriptworker-shipit
            os: scriptworker
            worker-type:
                by-level:
                    "3": xpi-3-shipit
                    default: xpi-1-shipit

github_clone_secret: project/xpi/xpi-github-clone-ssh

scriptworker:
    scope-prefix: project:xpi:releng
    signing-format:
        by-xpi-type:
            privileged: privileged_webextension
            system: system_addon
            mozillaonline-privileged: privileged_webextension

release-promotion:
    flavors:
        build:
            target-tasks-method: build_xpi
            rebuild-kinds:
                - build
                - test
                - dep-signing
        promote:
            target-tasks-method: promote_xpi
    notifications:
        # configure privileged webextension email addresses for
        # notifications
        privileged:
            by-phase:
                build: [aki+priv-webext-build@mozilla.com]
                promote: [aki+priv-webext-promote@mozilla.com]
        # configure system addons email addresses for notifications
        system:
            by-phase:
                build: [aki+system-addons-build@mozilla.com]
                promote: [aki+system-addons-promote@mozilla.com]
        # configure mozillaonline-privileged webextension email addresses for
        # notifications
        mozillaonline-privileged:
            by-phase:
                build: [aki+mozillaonline-priv-webext-build@mozilla.com]
                promote: [aki+mozillaonline-priv-webext-promote@mozilla.com]
