---
trust-domain: xpi
treeherder:
    group-names:
        'I': 'Docker Image Builds'
        'B': 'Builds'
        'T': 'Tests'
        'Ds': 'Development Signing'
        'Rs': 'Release Signing'

task-priority: lowest

taskgraph:
    register: xpi_taskgraph:register
    repositories:
        xpi:
            name: "XPI manifest"
    cached-task-prefix: xpi.xpi-manifest

workers:
    aliases:
        b-linux:
            provisioner: aws-provisioner-v1
            implementation: docker-worker
            os: linux
            worker-type: 'xpi-{level}-b-linux'
        images:
            provisioner: aws-provisioner-v1
            implementation: docker-worker
            os: linux
            worker-type: 'xpi-{level}-images'
        dep-signing:
            provisioner: scriptworker-prov-v1
            implementation: scriptworker-signing
            os: scriptworker
            worker-type: xpi-t-signing
        signing:
            provisioner: scriptworker-prov-v1
            implementation: scriptworker-signing
            os: scriptworker
            worker-type:
                by-level:
                    "3": xpi-3-signing
                    default: xpi-t-signing

github_clone_secret: project/xpi/xpi-github-clone-ssh

scriptworker:
    scope-prefix: project:xpi:releng
    signing-format:
        by-xpi-type:
            standard:
                by-kind:
                    dep-signing: extension_rsa
                    release-signing:
                        by-level:
                            "3": extension_rsa_rel
                            default: extension_rsa_dep
            system:
                by-kind:
                    dep-signing: systemaddon_rsa_dep
                    release-signing:
                        by-level:
                            "3": systemaddon_rsa_rel
                            default: systemaddon_rsa_dep

release-promotion:
    flavors:
        build:
            target-tasks-method: build_xpi
            rebuild-kinds:
                - build
                - test
                - dep-signing
        promote:
            target-tasks-method: promote_xpi
