---
trust-domain: garbage
scheduler-id: garbage-level-1

treeherder:
    group-names:
        'I': 'Docker Image Builds'

task-priority: lowest

workers:
    aliases:
        images:
            provisioner: aws-provisioner-v1
            implementation: docker-worker
            os: linux
            worker-type: 'github-worker'
        github-worker:
            provisioner: aws-provisioner-v1
            implementation: docker-worker
            os: linux
            worker-type: 'github-worker'
