---
description: Test template private repo with on-push/on-pr automation
repo-prefix: stagingprivate
active: true
private-repo: true
additional-emails: []
directory: one
branch: master
artifacts:
  - multipreffer-one.xpi
addon-type: normandy-privileged
install-type: npm
enable-github-release: True
release-tag: 1.0.7
release-name: releng-secret
